spring:
  rabbitmq:
    host: 192.168.88.100 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: itcast # 用户名
    password: 123321 # 密码
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS